import type {
  User,
  Group,
  Expense,
  Subscription,
  Settlement,
  LeaderboardEntry,
  MonthlySpend,
  CategoryBreakdown,
  AIInsight,
  Notification,
  AdminStats,
  RevenueEntry,
  Badge,
} from "./types";

// ─── Users ───────────────────────────────────────────────────────────────────

export const CURRENT_USER: User = {
  id: "user-1",
  name: "Mayank Gaur",
  email: "mayankgaur.8@gmail.com",
  plan: "pro",
  reputationScore: 92,
  paymentStreak: 14,
  badges: ["instant_payer", "reliable_flatmate", "streak_7", "early_adopter"],
  totalPaid: 24680,
  totalOwed: 3240,
  joinedAt: "2024-01-15",
  currency: "INR",
  isOnline: true,
};

export const MOCK_USERS: User[] = [
  CURRENT_USER,
  {
    id: "user-2",
    name: "Priya Sharma",
    email: "priya@example.com",
    plan: "pro",
    reputationScore: 88,
    paymentStreak: 7,
    badges: ["reliable_flatmate", "first_split"],
    totalPaid: 18420,
    totalOwed: 1200,
    joinedAt: "2024-02-01",
    currency: "INR",
    isOnline: true,
  },
  {
    id: "user-3",
    name: "Rahul Mehta",
    email: "rahul@example.com",
    plan: "free",
    reputationScore: 74,
    paymentStreak: 2,
    badges: ["first_split"],
    totalPaid: 9830,
    totalOwed: 4100,
    joinedAt: "2024-03-10",
    currency: "INR",
    isOnline: false,
  },
  {
    id: "user-4",
    name: "Ananya Patel",
    email: "ananya@example.com",
    plan: "pro",
    reputationScore: 96,
    paymentStreak: 30,
    badges: ["instant_payer", "streak_30", "budget_master"],
    totalPaid: 32100,
    totalOwed: 800,
    joinedAt: "2023-12-05",
    currency: "INR",
    isOnline: true,
  },
  {
    id: "user-5",
    name: "Karan Singh",
    email: "karan@example.com",
    plan: "team",
    reputationScore: 81,
    paymentStreak: 5,
    badges: ["group_creator", "social_butterfly"],
    totalPaid: 14200,
    totalOwed: 2800,
    joinedAt: "2024-01-20",
    currency: "INR",
    isOnline: false,
  },
];

// ─── Groups ───────────────────────────────────────────────────────────────────

export const MOCK_GROUPS: Group[] = [
  {
    id: "grp-1",
    name: "Koramangala Flat",
    description: "4 roommates, Bangalore",
    category: "flatmates",
    members: [
      { userId: "user-1", user: MOCK_USERS[0], role: "owner", balance: -2400, joinedAt: "2024-01-15" },
      { userId: "user-2", user: MOCK_USERS[1], role: "member", balance: 800, joinedAt: "2024-01-15" },
      { userId: "user-3", user: MOCK_USERS[2], role: "member", balance: 1200, joinedAt: "2024-01-15" },
      { userId: "user-4", user: MOCK_USERS[3], role: "member", balance: 400, joinedAt: "2024-01-15" },
    ],
    createdBy: "user-1",
    createdAt: "2024-01-15",
    totalExpenses: 128400,
    currency: "INR",
    inviteCode: "KORM2024",
    isArchived: false,
  },
  {
    id: "grp-2",
    name: "Goa Trip 🏖️",
    description: "5 friends, March 2024",
    category: "travel",
    members: [
      { userId: "user-1", user: MOCK_USERS[0], role: "owner", balance: 3200, joinedAt: "2024-03-01" },
      { userId: "user-2", user: MOCK_USERS[1], role: "member", balance: -1800, joinedAt: "2024-03-01" },
      { userId: "user-5", user: MOCK_USERS[4], role: "member", balance: -1400, joinedAt: "2024-03-01" },
    ],
    createdBy: "user-1",
    createdAt: "2024-03-01",
    totalExpenses: 42000,
    currency: "INR",
    inviteCode: "GOA2024",
    isArchived: false,
  },
  {
    id: "grp-3",
    name: "OTT Subscriptions",
    description: "Netflix, Prime, Spotify pool",
    category: "subscriptions",
    members: [
      { userId: "user-1", user: MOCK_USERS[0], role: "owner", balance: 240, joinedAt: "2024-01-01" },
      { userId: "user-3", user: MOCK_USERS[2], role: "member", balance: -80, joinedAt: "2024-01-01" },
      { userId: "user-4", user: MOCK_USERS[3], role: "member", balance: -80, joinedAt: "2024-01-01" },
      { userId: "user-5", user: MOCK_USERS[4], role: "member", balance: -80, joinedAt: "2024-01-01" },
    ],
    createdBy: "user-1",
    createdAt: "2024-01-01",
    totalExpenses: 4800,
    currency: "INR",
    inviteCode: "OTT2024",
    isArchived: false,
  },
  {
    id: "grp-4",
    name: "Startup Office",
    description: "Team expenses & utilities",
    category: "team",
    members: [
      { userId: "user-1", user: MOCK_USERS[0], role: "admin", balance: -5200, joinedAt: "2024-02-01" },
      { userId: "user-4", user: MOCK_USERS[3], role: "owner", balance: 2800, joinedAt: "2024-02-01" },
      { userId: "user-5", user: MOCK_USERS[4], role: "admin", balance: 2400, joinedAt: "2024-02-01" },
    ],
    createdBy: "user-4",
    createdAt: "2024-02-01",
    totalExpenses: 84000,
    currency: "INR",
    inviteCode: "STARTUP24",
    isArchived: false,
  },
];

// ─── Expenses ─────────────────────────────────────────────────────────────────

export const MOCK_EXPENSES: Expense[] = [
  {
    id: "exp-1",
    groupId: "grp-1",
    title: "February Rent",
    amount: 80000,
    currency: "INR",
    category: "rent",
    splitType: "equal",
    splits: [
      { userId: "user-1", amount: 20000, isPaid: true, paidAt: "2024-02-01" },
      { userId: "user-2", amount: 20000, isPaid: true, paidAt: "2024-02-02" },
      { userId: "user-3", amount: 20000, isPaid: false },
      { userId: "user-4", amount: 20000, isPaid: true, paidAt: "2024-02-01" },
    ],
    paidBy: "user-1",
    createdBy: "user-1",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
    isRecurring: true,
    recurringInterval: "monthly",
    nextDueDate: "2024-03-01",
    tags: ["rent", "monthly"],
  },
  {
    id: "exp-2",
    groupId: "grp-1",
    title: "Electricity Bill",
    amount: 3200,
    currency: "INR",
    category: "utilities",
    splitType: "equal",
    splits: [
      { userId: "user-1", amount: 800, isPaid: true },
      { userId: "user-2", amount: 800, isPaid: true },
      { userId: "user-3", amount: 800, isPaid: false },
      { userId: "user-4", amount: 800, isPaid: true },
    ],
    paidBy: "user-2",
    createdBy: "user-2",
    createdAt: "2024-02-05",
    updatedAt: "2024-02-05",
    isRecurring: false,
    tags: ["utilities"],
  },
  {
    id: "exp-3",
    groupId: "grp-2",
    title: "Beach Resort Hotel",
    amount: 18000,
    currency: "INR",
    category: "travel",
    splitType: "equal",
    splits: [
      { userId: "user-1", amount: 6000, isPaid: true },
      { userId: "user-2", amount: 6000, isPaid: false },
      { userId: "user-5", amount: 6000, isPaid: false },
    ],
    paidBy: "user-1",
    createdBy: "user-1",
    createdAt: "2024-03-15",
    updatedAt: "2024-03-15",
    isRecurring: false,
    tags: ["hotel", "goa"],
  },
  {
    id: "exp-4",
    groupId: "grp-3",
    title: "Netflix Premium",
    amount: 649,
    currency: "INR",
    category: "subscriptions",
    splitType: "equal",
    splits: [
      { userId: "user-1", amount: 163, isPaid: true },
      { userId: "user-3", amount: 163, isPaid: true },
      { userId: "user-4", amount: 163, isPaid: true },
      { userId: "user-5", amount: 160, isPaid: false },
    ],
    paidBy: "user-1",
    createdBy: "user-1",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
    isRecurring: true,
    recurringInterval: "monthly",
    nextDueDate: "2024-03-01",
    tags: ["netflix", "streaming"],
  },
];

// ─── Subscriptions ────────────────────────────────────────────────────────────

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "sub-1",
    name: "Netflix",
    logo: "🎬",
    color: "#E50914",
    monthlyCost: 649,
    currency: "INR",
    billingCycle: "monthly",
    renewalDate: "2024-03-01",
    groupId: "grp-3",
    sharedWith: ["user-1", "user-3", "user-4", "user-5"],
    costPerPerson: 163,
    category: "streaming",
    isActive: true,
    autoRenew: true,
    usageScore: 85,
    lastUsed: "2024-02-28",
  },
  {
    id: "sub-2",
    name: "Spotify Premium",
    logo: "🎵",
    color: "#1DB954",
    monthlyCost: 119,
    currency: "INR",
    billingCycle: "monthly",
    renewalDate: "2024-03-05",
    groupId: "grp-3",
    sharedWith: ["user-1", "user-3"],
    costPerPerson: 60,
    category: "music",
    isActive: true,
    autoRenew: true,
    usageScore: 92,
    lastUsed: "2024-02-28",
  },
  {
    id: "sub-3",
    name: "Amazon Prime",
    logo: "📦",
    color: "#FF9900",
    monthlyCost: 299,
    currency: "INR",
    billingCycle: "monthly",
    renewalDate: "2024-03-10",
    groupId: "grp-3",
    sharedWith: ["user-1", "user-4", "user-5"],
    costPerPerson: 100,
    category: "streaming",
    isActive: true,
    autoRenew: true,
    usageScore: 60,
    lastUsed: "2024-02-20",
  },
  {
    id: "sub-4",
    name: "ChatGPT Plus",
    logo: "🤖",
    color: "#10A37F",
    monthlyCost: 1674,
    currency: "INR",
    billingCycle: "monthly",
    renewalDate: "2024-03-15",
    sharedWith: ["user-1"],
    costPerPerson: 1674,
    category: "productivity",
    isActive: true,
    autoRenew: true,
    usageScore: 95,
    lastUsed: "2024-02-28",
  },
  {
    id: "sub-5",
    name: "Hotstar Premium",
    logo: "⭐",
    color: "#1A75BB",
    monthlyCost: 299,
    currency: "INR",
    billingCycle: "monthly",
    renewalDate: "2024-03-08",
    groupId: "grp-3",
    sharedWith: ["user-1", "user-3", "user-4"],
    costPerPerson: 100,
    category: "streaming",
    isActive: true,
    autoRenew: false,
    usageScore: 35,
    lastUsed: "2024-01-15",
  },
  {
    id: "sub-6",
    name: "Notion Pro",
    logo: "📝",
    color: "#000000",
    monthlyCost: 800,
    currency: "INR",
    billingCycle: "monthly",
    renewalDate: "2024-03-20",
    groupId: "grp-4",
    sharedWith: ["user-1", "user-4", "user-5"],
    costPerPerson: 267,
    category: "productivity",
    isActive: true,
    autoRenew: true,
    usageScore: 88,
    lastUsed: "2024-02-28",
  },
];

// ─── Settlements ──────────────────────────────────────────────────────────────

export const MOCK_SETTLEMENTS: Settlement[] = [
  {
    id: "set-1",
    fromUserId: "user-3",
    toUserId: "user-1",
    amount: 20000,
    currency: "INR",
    status: "pending",
    groupId: "grp-1",
    createdAt: "2024-02-10",
    note: "February rent",
  },
  {
    id: "set-2",
    fromUserId: "user-2",
    toUserId: "user-1",
    amount: 6000,
    currency: "INR",
    status: "pending",
    groupId: "grp-2",
    createdAt: "2024-03-16",
    note: "Goa hotel",
  },
  {
    id: "set-3",
    fromUserId: "user-1",
    toUserId: "user-4",
    amount: 2800,
    currency: "INR",
    status: "completed",
    method: "upi",
    groupId: "grp-4",
    createdAt: "2024-02-15",
    completedAt: "2024-02-15",
    transactionId: "UPI2024021512345",
  },
  {
    id: "set-4",
    fromUserId: "user-5",
    toUserId: "user-1",
    amount: 6000,
    currency: "INR",
    status: "pending",
    groupId: "grp-2",
    createdAt: "2024-03-16",
  },
];

// ─── Gamification ─────────────────────────────────────────────────────────────

export const ALL_BADGES: Badge[] = [
  {
    id: "instant_payer",
    name: "Instant Payer",
    description: "Settled payments within 1 hour, 5 times",
    icon: "⚡",
    color: "#F59E0B",
    rarity: "rare",
    unlockedAt: "2024-01-20",
  },
  {
    id: "reliable_flatmate",
    name: "Reliable Flatmate",
    description: "Never missed a rent payment for 3 months",
    icon: "🏠",
    color: "#10B981",
    rarity: "common",
    unlockedAt: "2024-04-01",
  },
  {
    id: "rent_king",
    name: "Rent King",
    description: "Paid rent on time for 12 consecutive months",
    icon: "👑",
    color: "#8B5CF6",
    rarity: "epic",
  },
  {
    id: "budget_master",
    name: "Budget Master",
    description: "Reduced monthly spending by 20%",
    icon: "💰",
    color: "#06B6D4",
    rarity: "rare",
  },
  {
    id: "social_butterfly",
    name: "Social Butterfly",
    description: "Active in 5+ groups simultaneously",
    icon: "🦋",
    color: "#EC4899",
    rarity: "common",
  },
  {
    id: "streak_7",
    name: "7-Day Streak",
    description: "Paid on time 7 days in a row",
    icon: "🔥",
    color: "#EF4444",
    rarity: "common",
    unlockedAt: "2024-01-22",
  },
  {
    id: "streak_30",
    name: "30-Day Streak",
    description: "Paid on time 30 days in a row",
    icon: "🔥",
    color: "#F97316",
    rarity: "rare",
  },
  {
    id: "streak_100",
    name: "Century Streak",
    description: "100-day payment streak",
    icon: "💯",
    color: "#8B5CF6",
    rarity: "legendary",
  },
  {
    id: "first_split",
    name: "First Split",
    description: "Created your first expense split",
    icon: "✂️",
    color: "#64748B",
    rarity: "common",
  },
  {
    id: "group_creator",
    name: "Group Creator",
    description: "Created 3 or more groups",
    icon: "👥",
    color: "#3B82F6",
    rarity: "common",
  },
  {
    id: "early_adopter",
    name: "Early Adopter",
    description: "Joined within the first month of launch",
    icon: "🚀",
    color: "#0EA5E9",
    rarity: "legendary",
    unlockedAt: "2024-01-15",
  },
  {
    id: "savings_guru",
    name: "Savings Guru",
    description: "Saved ₹10,000+ through AI optimization",
    icon: "🧠",
    color: "#10B981",
    rarity: "epic",
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, user: MOCK_USERS[3], score: 2480, streak: 30, totalPaid: 32100, change: "same" },
  { rank: 2, user: MOCK_USERS[0], score: 2210, streak: 14, totalPaid: 24680, change: "up" },
  { rank: 3, user: MOCK_USERS[1], score: 1980, streak: 7, totalPaid: 18420, change: "down" },
  { rank: 4, user: MOCK_USERS[4], score: 1640, streak: 5, totalPaid: 14200, change: "same" },
  { rank: 5, user: MOCK_USERS[2], score: 1120, streak: 2, totalPaid: 9830, change: "down" },
];

// ─── Analytics ────────────────────────────────────────────────────────────────

export const MONTHLY_SPEND: MonthlySpend[] = [
  { month: "Sep", total: 38200, rent: 20000, food: 8200, entertainment: 3000, subscriptions: 2800, other: 4200 },
  { month: "Oct", total: 42100, rent: 20000, food: 9400, entertainment: 4200, subscriptions: 2800, other: 5700 },
  { month: "Nov", total: 36800, rent: 20000, food: 7600, entertainment: 2800, subscriptions: 2800, other: 3600 },
  { month: "Dec", total: 51200, rent: 20000, food: 12000, entertainment: 8400, subscriptions: 2800, other: 8000 },
  { month: "Jan", total: 39600, rent: 20000, food: 8800, entertainment: 3200, subscriptions: 3240, other: 4360 },
  { month: "Feb", total: 44800, rent: 20000, food: 10200, entertainment: 5400, subscriptions: 3240, other: 5960 },
];

export const CATEGORY_BREAKDOWN: CategoryBreakdown[] = [
  { category: "Rent", amount: 20000, percentage: 44.6, color: "#0EA5E9" },
  { category: "Food", amount: 10200, percentage: 22.8, color: "#8B5CF6" },
  { category: "Entertainment", amount: 5400, percentage: 12.1, color: "#EC4899" },
  { category: "Subscriptions", amount: 3240, percentage: 7.2, color: "#10B981" },
  { category: "Transport", amount: 2800, percentage: 6.3, color: "#F59E0B" },
  { category: "Other", amount: 3160, percentage: 7.0, color: "#64748B" },
];

export const AI_INSIGHTS: AIInsight[] = [
  {
    id: "ins-1",
    type: "warning",
    title: "Hotstar barely used",
    description: "You've watched Hotstar only 3 times in the last 30 days. Consider canceling to save ₹100/month.",
    savingAmount: 100,
    actionLabel: "Cancel Subscription",
    createdAt: "2024-02-28",
  },
  {
    id: "ins-2",
    type: "saving",
    title: "Combine Netflix + Prime",
    description: "You can split costs with 1 more person to reduce your Netflix + Prime bill by ₹450/month.",
    savingAmount: 450,
    actionLabel: "Find Split Partner",
    createdAt: "2024-02-27",
  },
  {
    id: "ins-3",
    type: "recommendation",
    title: "December was 29% higher",
    description: "Holiday spending spike detected. Set a budget cap for December 2024 to avoid overspending.",
    actionLabel: "Set Budget",
    createdAt: "2024-01-01",
  },
  {
    id: "ins-4",
    type: "achievement",
    title: "On-time payment streak!",
    description: "You've paid 14 consecutive bills on time. You're in the top 8% of reliable payers.",
    createdAt: "2024-02-28",
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    type: "payment_due",
    title: "Rent due in 3 days",
    body: "Your share of ₹20,000 for Koramangala Flat is due on March 1st",
    isRead: false,
    createdAt: "2024-02-26",
    actionUrl: "/settlements",
  },
  {
    id: "notif-2",
    type: "payment_received",
    title: "Ananya paid you",
    body: "Ananya Patel settled ₹2,800 for Startup Office expenses",
    isRead: false,
    createdAt: "2024-02-25",
  },
  {
    id: "notif-3",
    type: "badge_earned",
    title: "New badge unlocked! 🔥",
    body: "You earned the 7-Day Streak badge. Keep it up!",
    isRead: true,
    createdAt: "2024-01-22",
  },
  {
    id: "notif-4",
    type: "subscription_renewal",
    title: "Netflix renews in 2 days",
    body: "Netflix Premium (₹649) renews on March 1st. Split cost with your group.",
    isRead: true,
    createdAt: "2024-02-27",
    actionUrl: "/subscriptions",
  },
  {
    id: "notif-5",
    type: "expense_added",
    title: "New expense in Goa Trip",
    body: "Karan Singh added 'Beach Resort Hotel' — your share is ₹6,000",
    isRead: true,
    createdAt: "2024-03-15",
    actionUrl: "/expenses",
  },
];

// ─── Admin ────────────────────────────────────────────────────────────────────

export const ADMIN_STATS: AdminStats = {
  totalUsers: 12842,
  activeUsers: 8924,
  totalRevenue: 284600,
  mrr: 47200,
  totalTransactions: 198430,
  totalGroups: 34210,
  proUsers: 3840,
  teamUsers: 420,
  churnRate: 4.2,
  nps: 72,
};

export const REVENUE_DATA: RevenueEntry[] = [
  { month: "Sep", mrr: 28000, newRevenue: 8400, churned: 1200, total: 28000 },
  { month: "Oct", mrr: 31200, newRevenue: 6800, churned: 1600, total: 31200 },
  { month: "Nov", mrr: 34800, newRevenue: 7200, churned: 1400, total: 34800 },
  { month: "Dec", mrr: 38400, newRevenue: 9200, churned: 2800, total: 38400 },
  { month: "Jan", mrr: 42800, newRevenue: 8600, churned: 1800, total: 42800 },
  { month: "Feb", mrr: 47200, newRevenue: 9400, churned: 1600, total: 47200 },
];
